apiVersion: v1
data:
  mapRoles: |

    - groups:
      - system:masters
      rolearn: arn:aws:iam::991968779966:role/UdacityFlaskDeployCBKubectlRole
      username: build 

    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::991968779966:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-OGMTUS3BXZ0J
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-04-27T20:46:37Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-04-27T20:46:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1433"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: c80e4e9e-31da-4853-9c35-09e58390a4dd
