apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::991968779966:role/UdacityFlaskDeployCBKubectlRole
      username: build     
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::991968779966:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1B3RJQBLGIGS9
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-04-27T13:22:54Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-04-27T13:22:54Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "6017"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: e2f2e9f5-529c-4265-978e-994e2cc5fa6c
